# Generated by Django 3.1 on 2020-08-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etablissement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='image_Dep',
            field=models.ImageField(default='img/img1.jpg', upload_to='img'),
        ),
    ]
