# Generated by Django 3.1 on 2020-08-16 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Etablissement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=12, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('specialite', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_image', models.ImageField(blank=True, default='default-avatar.png', null=True, upload_to='img/')),
                ('departement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Etablissement.departement')),
                ('filiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Etablissement.filiere')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
