# Generated by Django 3.1 on 2020-08-26 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Etablissement', '0002_auto_20200819_1818'),
        ('userProfiles', '0002_auto_20200816_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Etablissement.departement'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Etablissement.filiere'),
        ),
    ]
